version: "2.1"

services:
  db:
    image: mariadb:10
    container_name: "db"
    command: mysqld --sql_mode="STRICT_ALL_TABLES"
    env_file: ./.env

  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile-flask

    container_name: api
    env_file: ./.env

    links:
      - db

  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile-nginx

    container_name: frontend

    ports:
      - "${EXTERNAL_PORT:-8080}:80"

    links:
      - api
